# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
        ('request', '0004_alter_time_timezone_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oauth2.Client', verbose_name='client'),
        ),
    ]
